apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-01-04 - 09:50:06 +0000
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: k8sn-operator
    app.kubernetes.io/version: 1.0.0
  name: k8sn-operator
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: k8sn-operator
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
status:
  loadBalancer: {}
