apiVersion: v1
kind: Namespace
metadata:
  name:  infra
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: infra
type: Opaque
data:
  MYSQL_DATABASE: ZGI=  ##db
  MYSQL_USER: bXlzcWw=  ##mysql
  MYSQL_PASSWORD: bXlzcWxwYXNzIzEyMw==  ##mysqlpass#123
  MYSQL_ROOT_PASSWORD: bXlzcWxwYXNzIzEyMw==  ##mysqlpass#123

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deploy
  namespace: infra
  labels:
    k8s-app: mysql
    app: mysql
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: mysql
      app: mysql
  template:
    metadata:
      labels:
        k8s-app: mysql
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: http-port
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-vol
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: mysql-pvc-claim

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-svc
  namespace: infra
  labels:
    k8s-app: mysql
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: http-port
  selector:
    k8s-app: mysql
    app: mysql
